[build]
  command = "node build.js"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/factory/*"
  to = "/index.html"
  status = 200
  conditions = {Language = [], Country = [], Role = []}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
